/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module bin_to_dec #(
        parameter DIGITS = 3'h4,
        parameter LEADING_ZEROS = 1'h0
    ) (
        input wire [($clog2((64'(4'ha) ** (DIGITS))))-1:0] value,
        output reg [(DIGITS)-1:0][3:0] digits
    );
    logic [31:0] R_53cbe1cd_j;
    logic [31:0] RR_53cbe1cd_j;
    logic [31:0] R_03df23aa_i;
    logic [31:0] RR_03df23aa_i;
    logic [($bits(value))-1:0] L_6439eb07_remainder;
    logic L_6439eb07_blank;
    logic [($bits(value))-1:0] L_0fa6051f_scale;
    logic [($bits(value))-1:0] L_167ac8f7_sub_value;
    always @* begin
        digits = {DIGITS{{{4'hb}}}};
        L_6439eb07_remainder = value;
        L_6439eb07_blank = !LEADING_ZEROS;
        if (value < (64'(4'ha) ** (DIGITS))) begin
            for (RR_53cbe1cd_j = 0; RR_53cbe1cd_j < DIGITS; RR_53cbe1cd_j = RR_53cbe1cd_j + 1) begin
        R_53cbe1cd_j = (DIGITS - 1'h1) + RR_53cbe1cd_j * (-2'sh1);
                L_0fa6051f_scale = (64'(4'ha) ** (R_53cbe1cd_j));
                if (L_6439eb07_remainder < L_0fa6051f_scale) begin
                    if (R_53cbe1cd_j != 1'h0 && L_6439eb07_blank) begin
                        digits[R_53cbe1cd_j] = 4'ha;
                    end else begin
                        digits[R_53cbe1cd_j] = 1'h0;
                    end
                end else begin
                    L_6439eb07_blank = 1'h0;
                    L_167ac8f7_sub_value = 1'h0;
                    for (RR_03df23aa_i = 0; RR_03df23aa_i < 4'h9; RR_03df23aa_i = RR_03df23aa_i + 1) begin
            R_03df23aa_i = (4'h9) + RR_03df23aa_i * (-2'sh1);
                        if (L_6439eb07_remainder < (R_03df23aa_i + 1'h1) * L_0fa6051f_scale) begin
                            digits[R_53cbe1cd_j] = R_03df23aa_i;
                            L_167ac8f7_sub_value = R_03df23aa_i * L_0fa6051f_scale;
                        end
                    end
                    L_6439eb07_remainder = L_6439eb07_remainder - L_167ac8f7_sub_value;
                end
            end
        end
    end
    
    
endmodule