/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module alu_shifter (
        input wire [31:0] a,
        input wire [4:0] b,
        input wire [5:0] alufn,
        output reg [31:0] shift,
        output reg illop
    );
    logic [31:0] R_3a0b7df0_i;
    logic [31:0] RR_3a0b7df0_i;
    logic [31:0] R_1a46ebe7_i;
    logic [31:0] RR_1a46ebe7_i;
    logic [31:0] R_1f7dc7cd_i;
    logic [31:0] RR_1f7dc7cd_i;
    localparam logic [4:0][4:0] _MP_SHIFT_2103105164 = {{5'h10, 5'h8, 5'h4, 5'h2, 5'h1}};
    logic [4:0][31:0] M_xbls_a;
    logic [4:0] M_xbls_shift;
    logic [4:0] M_xbls_pad;
    logic [4:0][31:0] M_xbls_out;
    
    genvar idx_0_2103105164;
    
    generate
        for (idx_0_2103105164 = 0; idx_0_2103105164 < 5; idx_0_2103105164 = idx_0_2103105164 + 1) begin: forLoop_idx_0_2103105164
            alu_shifter_left #(
                .SHIFT(_MP_SHIFT_2103105164[idx_0_2103105164])
            ) xbls (
                .a(M_xbls_a[idx_0_2103105164]),
                .shift(M_xbls_shift[idx_0_2103105164]),
                .pad(M_xbls_pad[idx_0_2103105164]),
                .out(M_xbls_out[idx_0_2103105164])
            );
        end
    endgenerate
    
    
    localparam logic [4:0][4:0] _MP_SHIFT_272343572 = {{5'h10, 5'h8, 5'h4, 5'h2, 5'h1}};
    logic [4:0][31:0] M_xbrs_a;
    logic [4:0] M_xbrs_shift;
    logic [4:0] M_xbrs_pad;
    logic [4:0][31:0] M_xbrs_out;
    
    genvar idx_0_272343572;
    
    generate
        for (idx_0_272343572 = 0; idx_0_272343572 < 5; idx_0_272343572 = idx_0_272343572 + 1) begin: forLoop_idx_0_272343572
            alu_shifter_right #(
                .SHIFT(_MP_SHIFT_272343572[idx_0_272343572])
            ) xbrs (
                .a(M_xbrs_a[idx_0_272343572]),
                .shift(M_xbrs_shift[idx_0_272343572]),
                .pad(M_xbrs_pad[idx_0_272343572]),
                .out(M_xbrs_out[idx_0_272343572])
            );
        end
    endgenerate
    
    
    localparam logic [4:0][4:0] _MP_SHIFT_159549279 = {{5'h10, 5'h8, 5'h4, 5'h2, 5'h1}};
    logic [4:0][31:0] M_xbras_a;
    logic [4:0] M_xbras_shift;
    logic [4:0] M_xbras_pad;
    logic [4:0][31:0] M_xbras_out;
    
    genvar idx_0_159549279;
    
    generate
        for (idx_0_159549279 = 0; idx_0_159549279 < 5; idx_0_159549279 = idx_0_159549279 + 1) begin: forLoop_idx_0_159549279
            alu_shifter_right_ari #(
                .SHIFT(_MP_SHIFT_159549279[idx_0_159549279])
            ) xbras (
                .a(M_xbras_a[idx_0_159549279]),
                .shift(M_xbras_shift[idx_0_159549279]),
                .pad(M_xbras_pad[idx_0_159549279]),
                .out(M_xbras_out[idx_0_159549279])
            );
        end
    endgenerate
    
    
    always @* begin
        M_xbls_a = {{32'h0, 32'h0, 32'h0, 32'h0, 32'h0}};
        M_xbls_shift = 1'h0;
        M_xbls_pad = 1'h0;
        M_xbrs_a = {{32'h0, 32'h0, 32'h0, 32'h0, 32'h0}};
        M_xbrs_shift = 1'h0;
        M_xbrs_pad = 1'h0;
        M_xbras_a = {{32'h0, 32'h0, 32'h0, 32'h0, 32'h0}};
        M_xbras_shift = 1'h0;
        M_xbras_pad = 1'h0;
        for (RR_3a0b7df0_i = 0; RR_3a0b7df0_i < 3'h5; RR_3a0b7df0_i = RR_3a0b7df0_i + 1) begin
      R_3a0b7df0_i = (0) + RR_3a0b7df0_i * (1);
            if (R_3a0b7df0_i == 1'h0) begin
                M_xbls_a[R_3a0b7df0_i] = a;
                M_xbls_shift[R_3a0b7df0_i] = b[R_3a0b7df0_i];
                M_xbls_pad[R_3a0b7df0_i] = 1'h0;
            end else begin
                M_xbls_a[R_3a0b7df0_i] = M_xbls_out[R_3a0b7df0_i - 1'h1];
                M_xbls_shift[R_3a0b7df0_i] = b[R_3a0b7df0_i];
                M_xbls_pad[R_3a0b7df0_i] = 1'h0;
            end
        end
        for (RR_1a46ebe7_i = 0; RR_1a46ebe7_i < 3'h5; RR_1a46ebe7_i = RR_1a46ebe7_i + 1) begin
      R_1a46ebe7_i = (0) + RR_1a46ebe7_i * (1);
            if (R_1a46ebe7_i == 1'h0) begin
                M_xbrs_a[R_1a46ebe7_i] = a;
                M_xbrs_shift[R_1a46ebe7_i] = b[R_1a46ebe7_i];
                M_xbrs_pad[R_1a46ebe7_i] = 1'h0;
            end else begin
                M_xbrs_a[R_1a46ebe7_i] = M_xbrs_out[R_1a46ebe7_i - 1'h1];
                M_xbrs_shift[R_1a46ebe7_i] = b[R_1a46ebe7_i];
                M_xbrs_pad[R_1a46ebe7_i] = 1'h0;
            end
        end
        for (RR_1f7dc7cd_i = 0; RR_1f7dc7cd_i < 3'h5; RR_1f7dc7cd_i = RR_1f7dc7cd_i + 1) begin
      R_1f7dc7cd_i = (0) + RR_1f7dc7cd_i * (1);
            if (R_1f7dc7cd_i == 1'h0) begin
                M_xbras_a[R_1f7dc7cd_i] = a;
                M_xbras_shift[R_1f7dc7cd_i] = b[R_1f7dc7cd_i];
                M_xbras_pad[R_1f7dc7cd_i] = a[5'h1f];
            end else begin
                M_xbras_a[R_1f7dc7cd_i] = M_xbras_out[R_1f7dc7cd_i - 1'h1];
                M_xbras_shift[R_1f7dc7cd_i] = b[R_1f7dc7cd_i];
                M_xbras_pad[R_1f7dc7cd_i] = a[5'h1f];
            end
        end
        illop = 1'h0;
        
        case (alufn[1'h1:1'h0])
            2'h0: begin
                shift = M_xbls_out[3'h4];
            end
            2'h1: begin
                shift = M_xbrs_out[3'h4];
            end
            2'h3: begin
                shift = M_xbras_out[3'h4];
            end
            default: begin
                shift = 1'h0;
                illop = 1'h1;
            end
        endcase
    end
    
    
endmodule