/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module bin_to_dec #(
        parameter DIGITS = 3'h4,
        parameter LEADING_ZEROS = 1'h0
    ) (
        input wire [($clog2((64'(4'ha) ** (DIGITS))))-1:0] value,
        output reg [(DIGITS)-1:0][3:0] digits
    );
    logic [31:0] R_3b530582_j;
    logic [31:0] RR_3b530582_j;
    logic [31:0] R_2e1d965c_i;
    logic [31:0] RR_2e1d965c_i;
    logic [($bits(value))-1:0] L_379db0f5_remainder;
    logic L_379db0f5_blank;
    logic [($bits(value))-1:0] L_25ff97b4_scale;
    logic [($bits(value))-1:0] L_0b8ae3ab_sub_value;
    always @* begin
        digits = {DIGITS{{{4'hb}}}};
        L_379db0f5_remainder = value;
        L_379db0f5_blank = !LEADING_ZEROS;
        if (value < (64'(4'ha) ** (DIGITS))) begin
            for (RR_3b530582_j = 0; RR_3b530582_j < DIGITS; RR_3b530582_j = RR_3b530582_j + 1) begin
        R_3b530582_j = (DIGITS - 1'h1) + RR_3b530582_j * (-2'sh1);
                L_25ff97b4_scale = (64'(4'ha) ** (R_3b530582_j));
                if (L_379db0f5_remainder < L_25ff97b4_scale) begin
                    if (R_3b530582_j != 1'h0 && L_379db0f5_blank) begin
                        digits[R_3b530582_j] = 4'ha;
                    end else begin
                        digits[R_3b530582_j] = 1'h0;
                    end
                end else begin
                    L_379db0f5_blank = 1'h0;
                    L_0b8ae3ab_sub_value = 1'h0;
                    for (RR_2e1d965c_i = 0; RR_2e1d965c_i < 4'h9; RR_2e1d965c_i = RR_2e1d965c_i + 1) begin
            R_2e1d965c_i = (4'h9) + RR_2e1d965c_i * (-2'sh1);
                        if (L_379db0f5_remainder < (R_2e1d965c_i + 1'h1) * L_25ff97b4_scale) begin
                            digits[R_3b530582_j] = R_2e1d965c_i;
                            L_0b8ae3ab_sub_value = R_2e1d965c_i * L_25ff97b4_scale;
                        end
                    end
                    L_379db0f5_remainder = L_379db0f5_remainder - L_0b8ae3ab_sub_value;
                end
            end
        end
    end
    
    
endmodule