# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10.xci
# IP: The module: 'clk_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10.xci
# IP: The module: 'clk_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yourmum/Downloads/fpga-pain/fpga-pain/cores/clk_10/clk_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
